# Generated by Django 3.0.8 on 2020-08-03 07:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(default='default.jpg', upload_to='projects_thumbnails')),
                ('project_title', models.CharField(max_length=100)),
                ('project_summary', models.TextField()),
                ('github_link', models.CharField(blank=True, max_length=500, null=True)),
                ('post_link', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projects_cover_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_name', models.CharField(max_length=50)),
                ('cover_image', models.ImageField(default='default.jpg', upload_to='projects_cvr')),
                ('page_heading', models.CharField(max_length=100)),
                ('page_subheading', models.TextField()),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
