# Generated by Django 3.0.8 on 2020-08-05 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects_sec', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='projects_cover_info',
            name='cover_image',
        ),
    ]
