# Generated by Django 3.0.8 on 2020-08-02 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimaryUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_bg', models.ImageField(default='default.jpg', upload_to='home_bg')),
                ('name', models.CharField(max_length=50)),
                ('fancy_name', models.CharField(max_length=50)),
                ('bio', models.TextField()),
                ('status', models.TextField()),
                ('pfp', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('location', models.CharField(max_length=20)),
                ('twitter', models.URLField(max_length=300)),
                ('github', models.URLField(max_length=300)),
                ('discord', models.URLField(max_length=300)),
                ('linkdin', models.URLField(max_length=300)),
                ('email_id', models.EmailField(max_length=50)),
                ('recent_project_title', models.CharField(max_length=100)),
                ('recent_project_sub_title', models.CharField(max_length=150)),
                ('recent_project_summary', models.TextField()),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
