# Generated by Django 3.0.8 on 2020-08-05 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primaryuser',
            name='home_bg',
        ),
        migrations.RemoveField(
            model_name='primaryuser',
            name='pfp',
        ),
    ]
