# Generated by Django 3.0.8 on 2020-08-02 20:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_name', models.CharField(max_length=50)),
                ('cover_image', models.ImageField(default='default.jpg', upload_to='about_cvr')),
                ('micro_greeting_1', models.CharField(blank=True, max_length=50, null=True)),
                ('micro_greeting_2', models.CharField(blank=True, max_length=50, null=True)),
                ('short_intro', models.CharField(blank=True, max_length=50, null=True)),
                ('greeting_heading', models.CharField(max_length=50)),
                ('greeting_subheading', models.CharField(blank=True, max_length=50, null=True)),
                ('self_intro', models.TextField()),
                ('fairwell_words', models.TextField()),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
